#!/usr/bin/env bash

# slightly scuffed wallpaper picker menu for use with pywal - uses nsxiv if installed, otherwise uses dmenu

FOLDER=~/wallpapers                           # wallpaper folder
SCRIPT=~/.config/hypr/scripts/walset_backend # script to run after wal for refreshing programs, etc.

menu() {
  if command -v nsxiv >/dev/null; then
    CHOICE=$(nsxiv -otb $FOLDER/*)
  else
    CHOICE=$(echo -e "Random\n$(command ls -v $FOLDER)" | dmenu -c -l 15 -i -p "Wallpaper: ")
  fi

  case $CHOICE in
  Random) wal -i "$FOLDER" -o $SCRIPT ;; # dmenu random option
  *.*) wal -i "$CHOICE" -o $SCRIPT ;;
  *) exit 0 ;;
  esac

  notify-send "Changing Theme"
}

# If given arguments:
# First argument will be used by pywal as wallpaper/dir path
# Second will be used as theme (use wal --theme to view built-in themes)

case "$#" in
0) menu ;;
1) wal -i "$1" -o $SCRIPT ;;
2) wal -i "$1" --theme $2 -o $SCRIPT ;;
*) exit 0 ;;
esac

awww img "$CHOICE" -t wipe --transition-fps 60

wal -r

if pgrep -x quickshell >/dev/null; then
  pkill quickshell
  quickshell >/dev/null 2>&1 &
  notify-send "Quickshell refreshed"
fi

if pgrep -x waybar >/dev/null; then
  pkill waybar
  waybar >/dev/null 2>&1 &
  notify-send "Waybar refreshed"
fi

pkill swaync
swaync >/dev/null 2>&1 &

python /home/piyush/.local/bin/conkycolorspython.py

notify-send "Theme Changed"
