source = $HOME/.cache/wal/colors-hyprland.conf
source = $HOME/Pictures/wallpapers/.current-blurred.jpg

$currentWall = $HOME/Pictures/wallpapers/.current-blurred.jpg
$accent = @color2
$accentAlpha = @color5
$font = icomoon
$text = @color5

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
    screencopy_mode = 0
}

# BACKGROUND
background {
    monitor =
    path = $currentWall
    blur_passes = 2
    color = $base
}

# DATE
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $color2
    font_size = 12
    font_family = $font
    position = 0,10
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $color2
    font_size = 30
    font_family = $font
    position = 0, 45
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 90, 40
    rounding = 2
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $color2
    inner_color = $color2
    font_color = $color0
    fade_on_empty = false
    placeholder_text = ...
    hide_input = false
    check_color = $color5
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}
