-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
--   print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html
--
-- Conky Lua API: https://conky.cc/lua

-- Configuration settings: https://conky.cc/config_settings
conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'black',
    default_outline_color = 'black',
    default_shade_color = color2,
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = true,
    extra_newline = false,
    font = 'monospace:size=10',
    gap_x = 20,
    gap_y = 20,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = true,
    out_to_x = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'panel',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    own_window_transparent = true,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
        color0 = '#100a17', 
  	    color1 = '#6D5091',
        color2 = '#6B5A91',
        color3 = '#9C6697',
        color4 = '#AE6F96',
        color5 = '#9369AE',
        color6 = '#AD63AD',
        color7 = '#c3c1c5',
        color8 = '#62596d',
}

-- Variables: https://conky.cc/variables
conky.text = [[
${color1}${time %H:%M:%S} ${exec date +"%A"}
─────────────────
${color3}${exec date +"%d %B %G"}

]];
